### ISSUE TITLE
Convert roadmap into issues

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#178]
**What's the problem you want solved?**
We have a great roadmap but there aren't Github issues for the outstanding tasks.

**Is there a solution you'd like to recommend?**
Convert remaining points on roadmap into issues to track progress and document roadblocks and speed bumps.

Shall we rename to cycle map lol? I hate :car:

**Comment by christianbundy** [comment]
@cinnamon-bun I don't remember where it was, but I could've sworn that you wrote up a guide that had some concepts of 'levels' of different features. Like maybe publishing and liking is level 1, content warnings are level 2, editing messages is level 3, etc. I'm imagining it like a circle where the core stuff is level 1. Does that ring any bells, or was that a fever dream?

It's most important to me that bugs are resolved and that we can get to feature parity with Patchwork, and I'd like to try labeling which things are necessary for Patchwork parity and which are post-Patchwork features that I can push onto the back-burner.

I guess this also brings up the question of how many issues we want to keep open at a time, or what the right time horizon is for planning. I think I feel stressed when I see the issues start to pile up, but maybe that's a good thing because it means people are thinking about the far future? Having some basic way to organize this would probably be :key:, at least for figuring out which problems need to get resolved ASAP.

**Comment by christianbundy** [comment]
Found it! https://hackmd.io/sPidj-ZBS_anldK7Li-pyQ#Client-API--library-functions-and-queries

I could've sworn there was some further organization about 'levels' or 'grades' or something, like WCAG levels, but maybe I made that part up. To use the WCAG levels as a metaphor, it feels to me like Oasis is barely reaching level A (basic stuff like `<label>`) and I want to make sure I don't fall down any AAA rabbit holes (sign language interpretation for audio). In Patchwork, we were just closing any issues that were inactive for long periods of time, but it would've felt better to say "this won't happen for at least a year and I don't think I can keep this on my todo list" and closing. :disappointed:

**Comment by cinnamon-bun** [comment]
@christianbundy I don't think I ever prioritized all those features, no.  It's a great idea though, and a good place to have the hard discussions about priorities.

If we ever had a planning call, we could do it then?
