### ISSUE TITLE
Rename 'reply', 'comment', or both

### ISSUE THREAD

**Issue by christianbundy** [fraction/oasis#27]
**What version of this package are you using?** N/A

**What problem do you want to solve?** "reply" and "comment" aren't great verbs

**What do you think is the correct solution to this problem?** We should give them good names! Is "fork" better? I'm struggling with how to express the difference between "add a post to extend the current thread" and "add a post as a tangent off of a message".

**Are you willing to submit a pull request to implement this change?** Yes!

**Comment by christianbundy** [comment]
Maybe "sub-thread"?

**Comment by jedahan** [comment]
I'm generally confused about threads. In the ux, I see "...replied to a forked thread" and I'm not sure what that means. Its some weird mix between twitter and zulip but somehow worse than both. I wonder if spending some time thinking about the UX we would love to see would help us with better verbs.

**Comment by christianbundy** [comment]
That "replied to a forked thread" is coming from Patchwork, right? In Oasis there are three actions:

- **Root:** Start a new thread by creating a message without any ancestors.
- **Comment:** Add a response to an entire thread (which is a **root** or **reply**, plus its comments).
- **Reply:** Add a response to a specific **comment**.

I think Patchwork uses the word 'fork' instead of 'reply', but there's also this other unrelated thing where you make a new root and reference a message which people *also* call a 'fork'.

Also worth noting: Patchwork doesn't support adding a **comment** to a **reply**, they just add another reply as a sibling. There's a good discussion about all of this here: `%d6YLxDcLgHvhpoZx2K5uZig6ht8lTAtbACKFRty7q6Y=.sha256`.

![image](https://user-images.githubusercontent.com/537700/71919848-70e2d700-313a-11ea-8d10-f0915138e18e.png)

In this case:

- **A:** root
- **B, C, D, E:** comments on **A**
- **m, x**: replies to **C**
- **n:** comment on **m**
- **y:** comment on **x**

**Comment by christianbundy** [comment]
Starting to lean toward 'tangent' instead of 'reply' or 'fork'. :thinking:

**Comment by georgeowell** [comment]
Ah this is so hard! 

I'm kind of really into "Tangent"

We naturally tend towards "Fork" because of our interest in software but Tangent seems to describe that action so much better.

## Tangent Definitions
> Diverging from an original purpose or course.

> Digressing suddenly from one course of action or thought and turning to another.

> Origin of tangent
1585–90; < Latin tangent- (stem of tangēns, present participle of tangere to touch) in phrase līnea tangēns touching line.

>  Making contact at a single point or along a line; touching but not intersecting.

>  A sudden digression or change of course.

**Comment by christianbundy** [comment]
So hard! The other thing I've been thinking is maybe just dropping the nice one-word actions and do "Comment on thread" and "Reply to message". You can't win! :man_shrugging:

**Comment by georgeowell** [comment]
> So hard! The other thing I've been thinking is maybe just dropping the nice one-word actions and do "Comment on thread" and "Reply to message". You can't win! man_shrugging

Should we perhaps try this strategy out and see if it works for people?

**Comment by christianbundy** [comment]
I'd merge it. +1

**Comment by masukomi** [comment]
I think Slack has been homing in on the right approach to this. 

Think of a thread as if it were a slack channel. I'm either replying to the channel or I'm creating a subthread off of a specific post. They're like Slack channels because everyone looking at it is going to see the stuff to the "channel" by default and only see the subthread stuff if they click into it.

Their "start a thread" button is conceptually good but doesn't apply well for us since we don't really have channels and we're already in a thread. Maybe "Start A Subthread" for that button and "Reply To Thread".

Alternately, steal from email "Reply" and "Reply all" People are familiar with these terms and if you saw them side by side you'd know what they do. There is the downside that they might think the "Reply" option would be a private message, so this probably isn't the best way to go.

Mostly I'd say, this is very much a solved problem with email, newsgroups, slack, etc... we should steal liberally from ideas that are already entrenched and have familiarity to users before they ever get to Patchwork.

note: I don't like "tangent" because a new person can't have any reasonable expectation of what clicking on a "tangent" button would do. I also think there would be difficult to translate accurately. It's a subtle word with a lot of baggage.

**Comment by cinnamon-bun** [comment]
How about:

```
Message 1   [Reply]
 |
 +  Message 1.1   [Reply]
 |
 +  Message 1.2   [Reply]
 |   |
 |   +  Message 1.2.1   [Reply]
 |   |
 |   +  [Add comment here (A)]
 |
 +  Message 1.3   [Reply]
 |
 +  [Add comment here (B)]
```

Each message has `Reply` which creates a sub-thread inside that message.

There's also a **free-floating** `Add comment here` button (not inside a message), at the end of each indented series of messages.

`Add comment here (A)` is the same action as `Reply` to its parent, Message 1.2.

`Add comment here (B)` is the same action as `Reply` to its parent, Message 1

All these buttons could actually be `<detail>` elements which unfold to reveal a textbox right where your message will end up.

**Comment by christianbundy** [comment]
Yes! I think that's the most elegant solution and it's what I'd like to do on a longer timeline. That makes the most sense, IMO, anything less is just a duct tape solution until we're there.

**Comment by masukomi** [comment]
I like the functionality in @cinnamon-bun 's diagram, but i think the wording of "add comment here"  and "reply"  doesn't give a new user any hints as to what exactly will happen when you click each. There may be some visual design cues that could be added to help, but those wouldn't help blind users.

**Comment by christianbundy** [comment]
Oh, it looks like I misunderstood that suggestion. I was imagining the "Add comment here" being like how GitHub just has a free-floating `<textarea>` at the bottom of each thread for you to add comments to. I think it'd be pretty reasonable to just do the same, plus a "reply to message" button that lets you do a fork-style reply.
