### ISSUE TITLE
Can't click images to view them

### ISSUE THREAD

**Issue by cinnamon-bun** [fraction/oasis#3]
Images have an `href` of

`http://localhost:3000/&Ft9HIgL08yuQEKKFGcermmb5nRxv/HQnw+t0vTYCb/g=.sha256`

...which gives a Not Found when you click on them.

The image `src` points to a working URL at
`http://localhost:8989/blobs/get/%26Ft9HIgL08yuQEKKFGcermmb5nRxv%2FHQnw%2Bt0vTYCb%2Fg%3D.sha256`

That's the same port and URL format that you get from Patchwork if you right-click and Copy Image URL.  Is there some kind of local blob server running on port 8989 next to the Oasis webserver at 3000?

**Comment by christianbundy** [comment]
Thanks for this bug report!

Yeah, the local blob server comes from ssb-ws and runs on port 8989. In the future I'd like to handle this manually so that we can server appropriately-sized avatar images instead of using gigantic images scaled down to avatar size. 

I think we just need to make a context menu to open images in Patchwork and then this should be resolved (see https://github.com/ssbc/ssb-markdown/pull/29).

**Comment by khimaros** [comment]
This might be trickier to support for use cases where oasis is running behind a reverse proxy. Consider this a nudge to consider that use case!

**Comment by christianbundy** [comment]
Nice catch! I think this is actually a problem with the ssb-markdown library screwing with image links. I have a PR open to fix it but it would break compatibility with Patchwork. Gotta fix that first, thanks for creating this issue!

**Comment by christianbundy** [comment]
Resolved in 2.1.3! :tada: Thanks for your patience on this.
