### ISSUE TITLE
help: how to post private posts? how to upload images? how to upload/set profile pic?

### ISSUE THREAD

**Issue by msiqu** [fraction/oasis#300]
I can't find upload tools while posting or to set a profile pic. I also can't see a form for posting private images. Maybe it's not implemented in UI yet? 

Is there a recommended workaround? (ie. via CLI or fiddling with the filesystem directly?)

**Comment by christianbundy** [comment]
Hey, thanks for trying this out. I've been implementing features during nights, weekends, and lunch breaks, so development has been slow and steady, but those are absolutely on the roadmap. Here are a few links you might find useful:

- Uploading blobs: https://github.com/fraction/oasis/issues/265
- Profile image: https://github.com/fraction/oasis/pull/277
- New private post: https://github.com/fraction/oasis/issues/301 (just made this)

Are there any other major pain points you have that don't already have issues?

I've been starting messages with an [SSB-CLI](https://github.com/fraction/ssb-cli) command:

```sh
ssb publish \
  --type post \
  --text "👋" \
  --recps "$(ssb whoami | jq .id)" \
  --recps "@2xkjAty6RSr5uhbAvi0rbVR2g9Bz+89qiKth48ECQBE=.ed25519"
```

This will create a new message between you and `@2xkjA...` that you'll be able to see in the UI so that you can publish a longer post in the thread. You can add up to 7 `--recps`, including yours, so the max is you plus six other people.

**Comment by georgeowell** [comment]
Closing as OP's questions were answered.
