### ISSUE TITLE
Spacing issue in text based browsers

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#329]
## What's the problem you want solved?
There are some issues with spacing between items when using Oasis in a text based browser. I tried Lynx.

![Screenshot from 2020-03-19 02-31-53](https://user-images.githubusercontent.com/18296993/77025806-f5977000-6989-11ea-9359-4df6f9ab5353.png)

As you can see, all the post action options at the top of each post ("CommentJSON...) is all smushed together. 

## Is there a solution you'd like to recommend?
Ensure spacing between post action options are maintained.

## What version or commit of Oasis are you using?
Latest

**Comment by christianbundy** [comment]
I think this is because we're using `display: flex` and lynx is rendering that as `display: inline`. :/

**Comment by nickwynja** [comment]
I dug into the CSS and the spacing between these elements is handled by `margin` which is why there isn't any spacing rendered in a text-based browser. (I noticed this in `w3m` as well.)

Currently there is a trailing space included in the translation string. A quick fix would be to include leading whitespace in the translation as well.

https://github.com/fraction/oasis/blob/64d60491b2192ec678499392123e1862bc0970de/src/views/i18n.js#L153-L160

**Comment by nickwynja** [comment]
Sorry, to add to above, it does seem like the separation of the footer from the section header is likely related to `display: flex`, while the spacing between the inline text is separate.
