### ISSUE TITLE
What is the intended use case of Oasis?

### ISSUE THREAD

**Issue by trashhalo** [fraction/oasis#33]
The readme is alittle unclear on where Oasis fits into the ecosystem. 

* Is it meant to be run locally as an alternative to patchwork?
* Is it meant to be hosted and used by multiple users?

I think clarifying this would help contributors make more meaningful commits.

**Comment by christianbundy** [comment]
Thanks for pointing this out, I'll brain dump a bit and hopefully there will be some nuggets of usefulness.

The backstory is that I spent lots of time using and developing Patchwork and Patchbay, but found both difficult to improve and maintain. When Matt broke up with Patchwork I looked around and realized that there weren't any other apps that I'd recommend for most people, so I started taking the two-pronged approach of:

- Take care of Patchwork and keep it on life support until a next-generation SSB interface is ready.
- Start building a next-generation interface that's easier to use / improve / maintain.

> Is it meant to be run locally as an alternative to patchwork?

Yeah, my personal use-case is an alternative to Patchwork that can either attach to an existing SSB service or start its own, plus I use [a branch](https://github.com/fraction/oasis/tree/public) that acts as a [public SSB viewer](https://oasis-demo.fraction.io/).

> Is it meant to be hosted and used by multiple users?

It could be hosted somewhere (and secured with *at least* a password and TLS) if you want to be able to post to the same feed from multiple devices, but this loses many of the benefits of SSB's offline-first design. I'm planning to add identity switching, so that you can choose which feed you're posting from, but I think I'd like to avoid Mastodon-style logins where you have to trust the server administrator not to use your private keys or read your encrypted messages.

I know that @arj03 is working on [SSB-Browser](https://github.com/arj03/ssb-browser-demo), where the entire SSB node runs directly in your browser, which might cover the "I want to try SSB but I don't want to install anything" use-case, but I think it would be best to assume that anyone using Oasis can be trusted with all of the information that Oasis knows. The public viewer use-case is an exception to that, but that's not in `master` yet.

Once all of the basics are covered I'd really like to look into something like [choo](https://github.com/choojs/choo), which would allow Oasis to run on the server over HTTP *or* completely in the browser just like SSB-Browser does, but I'm trying not to get ahead of myself.

What do you think?

**Comment by trashhalo** [comment]
What I got from your comment merged with context from the README:
> Friendly Scuttlebutt interface designed for simplicity and accessibility. This is an experimental client built with HTML, CSS, and Node.js without any front-end JavaScript. The goal is to build a maintainable foundation for the next generation of scuttlebutt clients.

**Comment by christianbundy** [comment]
cc: @jedahan / @georgeowell in case you haven't seen this

Would love to collab on improving the readme! I've started a few `rewrite-readme` branches aimed at improving this but haven't been able to formulate anything I'm happy with. Here's a take (I'm promising myself that I won't hit the backspace key):

> Oasis is a friendly web interface for Secure Scuttlebutt. Its interface is meant to be accessible to most people and most web browsers, and its code is meant to be accessible to most people with a basic understanding of HTML, CSS, and JavaScript. Oasis should be fun to use and improve, but at the end of the day it's just a tool to help you connect more closely with the people around you.

cc: @cinnamon-bun, most of my vision for this project has been inspired by your work and it would be great to have your help carving out a vision of the future (or at least a better readme) if you have time/interest

**Comment by georgeowell** [comment]
From my own perspective there should be three main goals of this project:

User safety/moderation tools
Onboarding UX
Maintainability

I would like to work on the README and documentation a bit also but I don't have much spoons.

**Comment by cinnamon-bun** [comment]
General agreement here with @christianbundy and @georgeowell, plus also

* Accessibility (screen readers etc)
* Clear descriptions throughout the interface describe how SSB works and the privacy implications of each action
* "Calm UX" settings e.g. disabling animated gifs, hiding notification numbers and like numbers, grayscale mode.  Like how the Mastodon client Pinafore has [wellness settings].(https://github.com/nolanlawson/pinafore/pull/1256)
* Attention to larger-scale social dynamics & wellness of the scuttlebutt ecosystem beyond just moderation.  Things like this [worksheet](http://humanetech.com/wp-content/uploads/2019/04/humane_design_worksheet.pdf) from the Center for Humane Technology, and the abuse-audit spreadsheet I made
