### ISSUE TITLE
2.15.0 Error: Request must be addressed to 127.0.0.1 ...

### ISSUE THREAD

**Issue by seekr** [fraction/oasis#396]
## What's the problem you want solved?
Since the latest update I can't access my hosted instance using my domain or server IP:

`Request must be addressed to 127.0.0.1 or localhost and non-GET requests must contain non-blob referer.`

## Is there a solution you'd like to recommend?
I don't know... Any guidance on this would be appreciated.

**Comment by christianbundy** [comment]
How do you have your server set up? That suggests to me that the app is listening on `localhost`, but you're accessing it from another IP?

**Comment by christianbundy** [comment]
e.g. here's my Caddyfile for oasis-demo.fraction.io

```Caddyfile
oasis-demo.fraction.io

proxy  / 127.0.0.1:3000
```

Any chance you have a reverse proxy and you're forwarding the HTTP host header?

**Comment by seekr** [comment]
> e.g. here's my Caddyfile for oasis-demo.fraction.io
> 
> ```
> oasis-demo.fraction.io
> 
> proxy  / 127.0.0.1:3000
> ```
> 
> Any chance you have a reverse proxy and you're forwarding the HTTP host header?

This is my caddyfile:

`````
oasis.***.*** {
        basicauth / ** ****
        proxy / localhost:3000 {
                transparent
        }
}
`````

I don't think I'm doing any of those 2 things, at least not willingly 🙈

**Comment by christianbundy** [comment]
I think the problem should be resolved with `transparent`, but I'm not sure whether that will let you publish messages. :thinking: 

```
oasis.***.*** {
        basicauth / ** ****
        proxy / localhost:3000
}
```

I think our options are:

- Add a command-line flag to set the external host, `oasis.***.***`, or
- Change the CSRF mitigation so that we use a token rather than checking the HTTP referrer, or
- Maybe something else?

I can give this a think. Sorry for breaking your use-case!

**Comment by seekr** [comment]
as you said: removing `transparent` let me load oasis but I can't publish (same error as before when hitting `publish` button)

**Comment by christianbundy** [comment]
Yeah, there are two checks:

- The HTTP host header
- The referrer header

When you start Oasis on `localhost` it knows to check for `localhost` / `127.0.0.1` for both headers. When you use `transparent`, Caddy rewrites the host header to `oasis.example.com` or whatever and the server thinks that you're launching a DNS rebind attack. If we remove `transparent`, it resolves the issue.

Unfortunately `transparent` doesn't have any effect on the referrer header, so we need to either:

- Add support for a referrer like `oasis.example.com` even when the server is listening on `localhost`,
- Change Oasis so that it doesn't check the referrer (this is a good idea, but [adds complexity elsewhere](https://en.wikipedia.org/wiki/Waterbed_theory)), or
- Figure something else out

**Comment by christianbundy** [comment]
I think this is resolved by #398 if you'd like to test that out!

cc: @kseistrup

**Comment by kseistrup** [comment]
Thanks for the cc, it looks exactly like the error I'm running into.

**Comment by seekr** [comment]
@christianbundy can't thank you enough! It is working for me now.

in case other less experienced in node users are here: if you're running oasis directly from the repo (`npm run start`) to set the flag you need to:

`npm run start -- --allow-host oasis.adomain.tld`

**Comment by treasuretron** [comment]
I'm setting this up for the first time, I should wait until #398 is merged, yeah?

I only need to be able to access Oasis within the local network, do I still need Caddy or should something like `npm run start -- --allow-host 192.168.0.115` work?

thanks!

**Comment by christianbundy** [comment]
@treasuretron Nope, you're good to go: `node . --host 192.168.0.115` works fine. This is only a problem when you want to run it through a proxy, where another process (caddy/nginx/etc) forwards traffic from `example.com` to `192.168.0.115` and your local server is like ":scream: I'm getting connections from a website I don't recognize!".

**Comment by treasuretron** [comment]
it works! Thanks @christianbundy!!
