### ISSUE TITLE
Render webtorrent video embed links

### ISSUE THREAD

**Issue by Powersource** [fraction/oasis#456]
## What's the problem you want solved?

Right now people can embed videos in posts but the videos can at most be 5MB due to the blob size limit and so most videos can't be posted here.

## Is there a solution you'd like to recommend?

If there's a link like I guess 

```
![my ted talk](magnet:asdf...)
```

then it should be rendered using https://webtorrent.io/

This is basically how https://joinpeertube.org/ works and seems to be working well.

Stuff to consider is to look up how peertube requires the torrents to be structured. What does the video file in the torrent need to be called? How are subtitles handled?

Major blocker for this that I just realized is that this requires clientside js :grimacing:

**Comment by christianbundy** [comment]
Thanks for posting this issue. The 5 MB size limit is frustrating, and I'd support removing it.

Torrents are neat, but it's a different protocol that Oasis would need to support, plus it'd downgrade our privacy since you could harvest the IP address of everyone who watches your video. This would also need to be added to SSB-Markdown, which handles our quirky Markdown extensions.

**Comment by Powersource** [comment]
prob for another client!
