### ISSUE TITLE
Show Markdown preview before submitting post or comment

### ISSUE THREAD

**Issue by cinnamon-bun** [fraction/oasis#67]
**What's the problem you want to solved?**
I want to know my Markdown works before I post it.  It's also nice to be prompted to re-read my message before posting it, for typos and to encourage reflection.

This also reduces the need for editable messages #64 

**Is there a solution you'd like to recommend?**
1. Change the "Submit" button to "Preview"
2. Clicking Preview reloads the page, preserving the text in the input box, and adds a new preview box below it with rendered markdown and a Submit button.  Users can keep writing/editing and hit Preview again, or can Submit.

Or we could go to a new screen showing just the editbox and preview, but I think users often refer back to the thread as they write.

I'd vote for making people Preview before they can Submit, because I think this extra moment of reflection reduces flamewars.

**Comment by christianbundy** [comment]
I'm sure this isn't super hard but it will require a bit of work so I've been putting it off, but I want to express that it *is* important to me and I think this is a really great idea.

**Comment by skyebend** [comment]
Just wanted to vote for this. I think it is the last thing keeping me from switching from patchwork. Since there is no 'undo' in an immutable log, I *really* want to see what my markdown looks like before posting, so I usually browse in oasis, but switch back to patchwork for a more complex post.

Let me know if anything I can do to help (review, test)
