### ISSUE TITLE
Use default scroll bar in Firefox

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#84]
## Browser
Firefox Browser - 72.0.2
Chromium Version - 79.0.3945.79

## What's the problem you want to solved?
In Firefox, Oasis seems to be using a scroll bar that looks quite different to the default Firefox scroll bar. This makes it difficult to scroll using a mouse or on a touchscreen. 

This doesn't happen in Chromium, Oasis's scroll bar remains the default.

These are going to be some very thin images:
### Default Firefox scroll bar
![Screenshot from 2020-01-26 21-47-12](https://user-images.githubusercontent.com/18296993/73142365-88501880-4085-11ea-8a99-61c54bfd1210.png)

### Scrollbar of Oasis in Firefox (Nord theme)
![Screenshot from 2020-01-26 21-47-25](https://user-images.githubusercontent.com/18296993/73142380-ab7ac800-4085-11ea-9223-d558b652607a.png)

**Comment by christianbundy** [comment]
Thanks for opening this issue! Could you expand on this bit?

> This makes it difficult to scroll using a mouse or on a touchscreen.

Would this be resolved by making the scrollbars bigger? The scrollbar colors were changed because they're used in themes, and usually the default scrollbar colors conflict with the theme colors, but It's important to me that the scrollbars are still easy to use.

Here are some screenshots of a random scrollbar with the theme + without the theme:

![Screenshot from 2020-01-26 14-02-09](https://user-images.githubusercontent.com/537700/73142519-7ef28c00-4044-11ea-86be-75a4067a86ca.png)
![Screenshot from 2020-01-26 14-01-51](https://user-images.githubusercontent.com/537700/73142520-7ef28c00-4044-11ea-9845-a20142eb14bf.png)

Put another way: how can we improve the scrollbars without breaking theme support?

**Comment by georgeowell** [comment]
Ah I probably jumped the gun on this a bit. I think it could be improved by being around 5 times longer than it currently is. This would make it very similar to the scrollbar on Mastodon which is probably fine. 

## Mastodon v3.0.1 Scroll Bar 
![Screenshot from 2020-01-26 22-26-11](https://user-images.githubusercontent.com/18296993/73142805-e3d0d500-408a-11ea-9903-c920a5baa54e.png)

**Comment by christianbundy** [comment]
Hmm, I don't think that's something that we have control over -- the scrollbar height is determined by the size of the webpage, so the bigger the webpage is the smaller the scrollbar is. Right now I think it shows 64 messages on each page, but I'm happy to reduce that once we have pagination working.

**Comment by georgeowell** [comment]
Ok that makes total sense now!

This suggests to me we have too many messages by default so I'm totally in favour of what you said. Perhaps thirty two is fine.

Closing.
