### ISSUE TITLE
Implement "Bookmarks" private likes 

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#86]
Sorry I'm not sure if this is outside the remit of this project but I thought it would be good to implement private likes which could referred to as Bookmarks.

I swear this was a thing on Mastodon but I [can't find it now](https://docs.joinmastodon.org/methods/accounts/bookmarks/).

Basically these would act alongside "Likes" in order to save content to a list for you to read later rather than a token of explicitly bestowing public favour upon a post. Ideally these wouldn't be revealed to other uses to reduce metadata.

Feel free to close if not likely to be in roadmap.

**Comment by arj03** [comment]
Isn't this a browser app, so you can use the existing book system or another system where you can patch in different things like other links and add comments (something like org mode)? :)

**Comment by cinnamon-bun** [comment]
Related discussion in #49 "Hide messages that you're done with" talking about stars, bookmarks, read/unread, etc

**Comment by georgeowell** [comment]
> Isn't this a browser app, so you can use the existing book system or another system where you can patch in different things like other links and add comments (something like org mode)? :)

Damn, that is a good idea. Currently it's a little tricky because you can't always click through on your feed to a post to get the full URI that you are looking for (currently unless it is a thread) e.g.

http://localhost:3000/thread/%25SLsk9rdtqKtPFcxl%2BHsdvWTUgNxButMuDFfLVOIKJc4%3D.sha256#%25SLsk9rdtqKtPFcxl%2BHsdvWTUgNxButMuDFfLVOIKJc4%3D.sha256

I wonder if there is way to make this more obvious that you can bookmark stuff in your browser. Though browser bookmarks kind of suck. I never end up going back to them unless they come up in the URL bar which wouldn't happen with a long key like that.

Also perhaps this stratergy wouldn't work if Oasis was packaged with Electron as a stand-alone app as mentioned in #42.

**Comment by arj03** [comment]
I think that if everything is links, then there shouldn't be problem using the url bar as bookmarks. I mean a lot of people do that for articles and stuff they want to read (but probably never will :))

**Comment by georgeowell** [comment]
The benefit of bookmarks being private message to yourself is that they are within SSB itself and can't be deleted or lost if you still have the key. They would also be portable between clients. 

Reloading a Firefox profile just for your old bookmarks can be hell :fire:

**Comment by christianbundy** [comment]
If someone wants to write an `{ type: "bookmark" }` specification and get community consensus and write a library to support it, I'd be open to having it included in Oasis, but I think that the prerequisites for this feature might be outside my idea of the scope of Oasis.

Maybe useful context: the thing that made the existing clients really hard for me to use is that they used a bunch of experimental technology and message types (labels :scream:) that weren't really supported by the rest of the community. These neat features ended up being burdens, and unless they're absolutely critical (i.e. it's a **big problem** that we don't have them) then I'd love to make sure we experiment them and make sure we have enough people to share the burden. It's really easy to add features and really hard to remove them, which is probably why I've been so curmudgeonly about 'solving problems' instead of looking for new features to add. :heart: 

[This chapter in particular](https://hintjens.gitbooks.io/social-architecture/content/chapter5.html) has been circling my brain non-stop recently, and probably informs lots of the ideas that I've been having about this project. I can't recommend *Social Architecture* enough.

**Comment by georgeowell** [comment]
Agreed. Closing.
