### ISSUE TITLE
Implement markdown WYSIWYG editor (including emojis)

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#90]
I'm not sure the most elegant way of doing this for Markdown but a lot of other stuff uses [CKeditor](https://ckeditor.com/). There is a [markdown plugin](https://ckeditor.com/cke4/addon/markdown) for what it's worth.

I'm not sure of the technicals of implementing something like this but I think its really necessary for non-technical users. It should also have an emoji picker.

## Mock up (from CKeditor website)
![home-product-screenshot-cke4-e0bcaaf64a](https://user-images.githubusercontent.com/18296993/73143163-a8d0a080-408e-11ea-890b-b60bd093836b.png)

**Comment by christianbundy** [comment]
I'd be open to adding individual components (add mention (#47), add blob, maybe 'add emoji') but I think I'd really like to take baby steps instead of adding a WYSIWYG editor. If you feel strongly about a WYSIWYG editor on the front-end, I think maybe the first step would be discussing removing the "no browser JavaScript" thing we advertise in the readme.

Another thought, maybe there's a browser extension that lets you convert `<textarea>` into a Markdown WYSIWYG?

**Comment by georgeowell** [comment]
This is pretty vague from me. Closing.
